#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          20
bspc config normal_border_color \#F0E68C
bspc config active_border_color \#F0E68C
bspc config focused_border_color \#F0E68C

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Processes #
#############

# Polybar (bar)
$HOME/.config/polybar/launch.sh

# feh (wallpaper)
feh --bg-fill $HOME/.config/bspwm/wallpapers/sky.jpg

# Compton (compositor)
compton -b
